### ISSUE TITLE
convert feature_scaling to transformer

### ISSUE THREAD

**Issue by Aylr** [HealthCatalyst/healthcareai-py#248]
- [ ] convert to transformer
- [ ] audit and increase tests if needed

**Comment by mxlei01** [comment]
Related to #276.

If we built a prediction and a training pipeline. What will happen is that the feature scaling will fit and transform on the training data (with it's own standard deviation and mean), and then feature scaling will fit and transform on testing data (then with it's own standard deviation and mean), which means it's going to break.

feature scaling needs to be re-used for the prediction_pipeline. The might need to take in another parameter for the full_pipeline function to re-use the feature scaling.

```
# Build the pipeline
pipeline = hcai_pipelines.full_pipeline(model_type, predicted_column, grain_column, impute=impute)
prediction_pipeline = hcai_pipelines.full_pipeline(model_type, predicted_column, grain_column, impute=True)
```

**Comment by mxlei01** [comment]
Pipeline also needs another variable to identify which columns to scale. By default, we can scale any columns that are numeric.
