### ISSUE TITLE
dummification fails if prediction dataframe contains only one row

### ISSUE THREAD

**Issue by Aylr** [HealthCatalyst/healthcareai-py#261]
## Background

If the categorical column like gender contains only one row, then it appears that the pandas.get_dummies() does not run on the model.

## Example code that should fail

```
import pandas as pd
import healthcareai.tests.helpers as helpers
from healthcareai.trainer import SupervisedModelTrainer

training_df = helpers.load_factors_dataframe()

hcai = SupervisedModelTrainer(training_df, 'has_diabetes', 'classification', impute=True, grain_column='id')

# Train the linear regression model
lr = hcai.logistic_regression()
new_data = pd.DataFrame({'id': [99], 'age': [50], 'gender': ['m'], 'weight': [250], 'a1c': [8], 'fbg': [120], 'has_diabetes': ['Y']})
new_data.head()
factors = lr.make_predictions(new_data)
```

**Comment by yvanhuele** [comment]
Is the column index from the training dataset stored somewhere?  If so, reindexing the prediction dataframe as described in this stackoverflow post might work:
https://stackoverflow.com/questions/28465633/easy-way-to-apply-transformation-from-pandas-get-dummies-to-new-data
