### ISSUE TITLE
for predictions null rows must not be dropped

### ISSUE THREAD

**Issue by Aylr** [HealthCatalyst/healthcareai-py#276]
See notes in `data_preparation.py`

## Things to think about

- When SupervisedModelTrainer is initialized, `impute` is set to `True` or `False` which determines if imputation happens or if rows with nulls are dropped.
- This is fine for training, but when a new prediction comes in, we probably *do not* want to drop a row if there are any null values.

## Possible untested solution

```
    def __init__(self, dataframe, predicted_column, model_type, impute=True, grain_column=None, verbose=False):
        self.grain_column = grain_column,
        self.predicted_column = predicted_column,
        self.grain_column = grain_column,
        self.grain_column = grain_column,

        # Build the pipeline
        training_pipeline = pipelines.full_pipeline(model_type, predicted_column, grain_column, impute=impute)
        prediction_pipeline = pipelines.full_pipeline(model_type, predicted_column, grain_column, impute=True)

        # Run the raw data through the data preparation pipeline
        clean_dataframe = training_pipeline.fit_transform(dataframe)
        _ = prediction_pipeline.fit_transform(dataframe)

        # Instantiate the advanced class
        self._advanced_trainer = AdvancedSupervisedModelTrainer(clean_dataframe, model_type, predicted_column,
                                                                grain_column, verbose)

        # Save the pipeline to the parent class
        self._advanced_trainer.pipeline = prediction_pipeline

        # Split the data into train and test
        self._advanced_trainer.train_test_split()
```

**Comment by mxlei01** [comment]
With impute=False, it looks like this line would fail if you would took a DataFrame that did not run through the impute process.

`results['Prediction'] = y_predictions`

Since if the rows are dropped, the number of predictions would shrink, so the number of predictions would not match.

**Comment by mxlei01** [comment]
Something to think about is impute=True on prediction. Impute might not be a good idea, and sometimes it's better to tell the users that some values are missing, and it will be imputed (or not by default).

To me, it's kind of strange to fill in data for prediction but you have some values for NaN for a regression task.

**Comment by Aylr** [comment]
I agree with you. I think we should force imputation for now!
