### ISSUE TITLE
make_predictions doesn't return correct grain column values of dataframe slices

### ISSUE THREAD

**Issue by yvanhuele** [HealthCatalyst/healthcareai-py#284]
Running given a dataframe df, an trained model trained_model, and a positive integer n, running make_predictions(df.iloc[n:]) performs predictions on the correct rows, but sets the grain_column value to NaN for the first n rows of the slice (so rows which are actually rows n to 2n - 1) and then starts labeling from the n-th grain column id onward.

For example, if trained_model.make_predictions(df) looks like
ID  Prediction
1  101
2  102
3  103
4  104
5  105
6  106

Then trained_model.make_predictions(df.iloc[2:]) looks like
ID  Prediction
NaN  103
NaN  104
3  105
4  106

note: make_predictions seems to work fine with slices of the form df.iloc[:n]

**Comment by Hanlei-Zhu** [comment]
I have the similar problem. When I try to use make_predictions(test), I get NaN in the grain_column. I did a small experiment to test the following code in trained_supervised_model.py. 
# Create a new dataframe with the grain column from the original dataframe
        results = pd.DataFrame()
        results[self.grain_column] = dataframe[self.grain_column]
        results['Prediction'] = y_predictions

For example, I create a new dataframe results = pd.DataFrame() and I have another dataframe df
df
   one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  5.0  4.0

Now if I run results['grain_col']=df['one'], what I get is 
>>> results
   one
0  NaN
1  NaN
2  NaN
3  NaN

But if I run results['grain_col']=df['one'].values, it works fine.
>>> results
   one
0  1.0
1  2.0
2  3.0
3  4.0

**Comment by Aylr** [comment]
Fantastic work!
