### ISSUE TITLE
Models To Compare plotting needs tuning, disambiguation in Advanced Example

### ISSUE THREAD

**Issue by EthanTaft** [HealthCatalyst/healthcareai-py#285]
When plotting the models in example_advanced.py with hcai_tsm.tsm_classification_comparison_plots, if two models are built of the same class, like two KNNs, the classification_comparison_plots command only plots one of the KNNs.  Also, in using the ensemble, when plotting the curves at the end, it only plots one curve, which I assume is the best one, but there isn't a chance for visual comparison.

Action Items
- Plot all items fed into the `trained_supervised_models = models_to_compare` command while giving the names of each.
       -Need to differentiate in the naming of such models on the graph, which one is which.

- When using `custom_ensemble` make sure that each model is printed in the `.roc_plot`

Possible Action Item
-Need to make sure that the plots in .roc_plot() represent the names of the models created. Diasmbiguate.

**Comment by Aylr** [comment]
Great discovery Ethan. Let's let issue #239 track the ensemble problem, and leave this issue to deal with the duplicate model names problem.
