### ISSUE TITLE
`writeData` fails if table schema is not default

### ISSUE THREAD

**Issue by mmastand** [HealthCatalyst/healthcareai-py#292]
I filed an issue [here](https://github.com/rstats-db/DBI/issues/181) and [here](https://stackoverflow.com/questions/44534986/how-does-one-write-to-an-ms-sql-table-with-specific-schema-from-r-using-dbi). 

Reading works fine from any table. Writing only works if the table schema is the DB default. I've been working on it with Joe and Jeff. We've been using RODBC's sqlSave as a workaround.

**Comment by Aylr** [comment]
Issue moved to [HealthCatalyst/healthcareai-r #492](https://github.com/HealthCatalyst/healthcareai-r/issues/492) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Aylr** [comment]
This issue belongs to the R repo
