### ISSUE TITLE
QuantifiedCode will be closing soon?

### ISSUE THREAD

**Issue by mxlei01** [HealthCatalyst/healthcareai-py#310]
It looks like QuantifiedCode will be shutting down soon.

A good alternative is: landscape.io and codeclimate

Both of them provide python code quality checks.

For code coverage, I had really good results with coveralls.io, and nosetests can be easily integrated with their API.

You can  also attach  coveralls.io, landscape.io, and github activities (pull requests) to a slack channel.

**Comment by Aylr** [comment]
I just heard this as well and I'm pretty sad. I'll check out landscape and codeclimate! I've been meaning to set up code coverage - that should be a separate issue - could you help me with that?

I do have our build systems set up to notify our internal slack - so helpful!

**Comment by mxlei01** [comment]
@Aylr I can help setup code coverage. It's very simple, and a one time process. Coveralls integrate with nosetests nicely. I can guide you through the process in this issue or slack.

**Comment by Aylr** [comment]
Let's follow up in slack!

**Comment by Aylr** [comment]
Closing please see #344
