### ISSUE TITLE
"Percentage imputed" is displaying twice when running example_classification_1.py random forest

### ISSUE THREAD

**Issue by Aylr** [HealthCatalyst/healthcareai-py#352]
@mxlei01 Can you take a look at this? I suspect that it isn't your code, but that your code is exposing some other repetition...

## STR
- [ ] modify `example_classification_1.py` to train a random forest model
- [ ] run the example
- [ ] note the output
- [ ] Note this is not an issue in `example_advanced.py`

```
...
3                   4      10002          187.0   135.0     4.4         M   
4                   5      10002          188.0   125.0     4.3         M   

  ThirtyDayReadmitFLG  
0                   N  
1                   N  
2                   N  
3                   N  
4                   N  
Percentage Imputed: 1.3171225937183384%
Percentage Imputed: 1.3171225937183384%

Training Random Forest Classification
RandomForestClassifier Training Results:
- Training time:
...
```

## Additional notes

- It would be nice to round this to 2 or three decimals

**Comment by mxlei01** [comment]
Ah, since I ran the imputation model, and did not run with the trainer. 

These two lines calls the imputation together:
        pipeline = hcai_pipelines.full_pipeline(model_type, predicted_column, grain_column, impute=impute)
        prediction_pipeline = hcai_pipelines.full_pipeline(model_type, predicted_column, grain_column, impute=True)

So it outputs three times.
