### ISSUE TITLE
Add additional healthcare datasets from UC Irvine ML Library?

### ISSUE THREAD

**Issue by jpo** [HealthCatalyst/healthcareai-py#363]
I'm curious if there is interest in adding additional ML sample data sets from the[ University of California Irvine ML Library](https://archive.ics.uci.edu/ml/index.php). There are many healthcare related data sets available, including the [Pima Indian Diabetes](https://archive.ics.uci.edu/ml/datasets/Pima+Indians+Diabetes) data set, which seems to be used often in introductory ML examples. I think it would be great to include these and possibly use them as examples of how to approach specific problems on the healthcare.ai blog.

**Comment by Aylr** [comment]
I'm all for this as long as long as we are judicious in choosing datasets - we don't want a dataset to drastically increase the size of the library. (MB, etc). Do you want to take this on @jpo? We'd love a guest blog if you're willing (and if not, no worries).

**Comment by jpo** [comment]
Absolutely. I'd be happy to take this on and contribute a guest post. I'll get to work!

**Comment by Aylr** [comment]
Note that in #372 a dermatology multiclass dataset is being added and should be in master soon.
