### ISSUE TITLE
Extract multiclass enhancements from sc_neuralnet branch plus feature & bugfix bonanza

### ISSUE THREAD

**Issue by Aylr** [HealthCatalyst/healthcareai-py#372]
Pull out the good multiclass work from the `sc_neuralnet` branch, test, document

- [x] modify classification metrics and only use roc & pr if binary
- [x] investigate and fix if needed duplicate `original_column_names` and `column_names`
- [x] remove neural net stuff and non-transformer feature scaling
- [x] for trainer, print out how many classes (and maybe a list of classes if length is reasonable) for classification tasks. `Training a Random Forest on 3 classes (iris, sunflower, nothotdog)`
- [x] Think about the best way to handle scoring metrics. For binary classification should it use `roc_auc`, or is `accuracy` an ok default (because it works with multiclass)?
- [x] tests for new SMT properties
- [x] tests for new ASMT properties
- [x] tests for errors on TSM binary only metrics (pr, auc, etc)
- [x] multiclass example file (including confusion matrix plot)
- [x] confusion matrix plot needs model name in title for differentiation
- [x] multiclass ensemble breaks
- [x] fix the confusion matrix plot so that long class labels are visible
- [x] multiclass documentation (including describing the confusion matrix example plot)
- [x] normalize via row the confusion matrix plot
- [x] for count confusion matrix plots, do not show color

## 'Y'/'N' Binary issue

- Note that the failure point seems to be in calculating ROC/PR, since they compare a 0-1 probability with a 0 or 1 label.
- This will require an argument, probably on SMT and ASMT like `positive_target_label` for binary classification tasks.

### Implementation Details

- [x] research the 'Y'/'N' binary issue
- [x] function to change first label to 1 and 2nd to  0
- [x] update docs by removing y/n crap
- [x] decide what to do if labels are nonsensical strings 'red'/'green' - what should happen?
- [x] implement optional argument for positive class
- [x] implement if label is specified, no guessing should occur
- [x] display console output on which is the positive class
- [x] display on plots which is the positive class
- [x] document which are assumed positive classes
- [ ] ~warn user if it looks like they got the wrong positive class (roc_auc < 0.5)~ https://github.com/HealthCatalyst/healthcareai-py/issues/387

**Comment by mmastand** [comment]
Done, last remaining issue is in #387
